describe('Register User Test cases', () => {
  it('should visits', () => {
    cy.visit('http://localhost:4200/auth/login')
    .wait(1000)
  })
  it('should give Username already exist error', () => {
    cy.visit('http://localhost:4200/auth/login')
    .wait(500)
    .get('a.cursor-pointer').click()
    .wait(1000)
    .get('#name').type('Mahamil')
    .wait(1000)
    .get('#username').type('Mahamil')
    .wait(1000)
    .get('#email').type('mahamil@abc.com')
    .wait(1000)
    .get('#phone').type('908990099')
    .wait(1000)
    .get('#password').type('password')
    .wait(1000)
    .get('#register-btn').click()
    .wait(2000)
    .get('#username-error').should('contain', 'Username must be unique')
    .wait(1000)
  })
  it('should gives User with email already exist exist error', () => {
    cy.visit('http://localhost:4200/auth/login')
    .wait(500)
    .get('a.cursor-pointer').click()
    .wait(1000)
    .get('#name').type('ABC')
    .wait(1000)
    .get('#username').type('abc')
    .wait(1000)
    .get('#email').type('mgadit@boggle.com')
    .wait(1000)
    .get('#phone').type('908990099')
    .wait(1000)
    .get('#password').type('password')
    .wait(1000)
    .get('#register-btn').click()
    .wait(2000)
    .get('#email-error').should('contain', 'User with email already exist')
    .wait(1000)
  })

  it('should register new user and navigate to login', () => {
    cy.visit('http://localhost:4200/auth/login')
    .wait(500)
    .get('a.cursor-pointer').click()
    .wait(1000)
    .get('#name').type('ABC')
    .wait(1000)
    .get('#username').type('abc')
    .wait(1000)
    .get('#email').type('abc@email.com')
    .wait(1000)
    .get('#phone').type('908990099')
    .wait(1000)
    .get('#password').type('123456')
    .wait(1000)
    .get('#register-btn').click()
    .wait(2000)
    .wait(1000)
    .url().should('eq', 'http://localhost:4200/auth/login')
    .wait(1000)
  })
})